# Generated by Django 3.2.13 on 2022-07-04 17:02

import actstream.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='action',
            managers=[
                ('objects', actstream.managers.ActionOnSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sites.site'),
            preserve_default=False,
        ),
    ]
